name: Test CI
on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'trigger'
        required: false
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run test commands
        run: |
          npm ci
          npm run test
          npm run test:coverage
        working-directory: ./server
